name: Windows build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      shell: bash
      run: |
           cmake -B _build -S . \
           -DCMAKE_BUILD_TYPE=Release
    - name: Build
      shell: bash
      run: |
             cmake --build _build --config Release
