name: Windows build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Install pre-requisites
      shell: cmd
      run: |
        choco install wget unzip zip --no-progress

    - name: Install ccache
      shell: bash
      run: |
        wget https://github.com/ccache/ccache/releases/download/v4.8.3/ccache-4.8.3-windows-x86_64.zip -O ccache.zip
        unzip ccache.zip
        rm ccache.zip
        mv ccache-4.8.3-windows-x86_64 ccache
        cp ccache/ccache.exe ccache/cl.exe
        echo "${GITHUB_WORKSPACE}/ccache" >> $GITHUB_PATH
        echo "CCACHE_DIR=${GITHUB_WORKSPACE}/ccache" >> $GITHUB_ENV

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: windows

    - name: Configure
      shell: bash
      run: |
           VERBOSE=1 cmake -B _build -S . \
           -DCMAKE_BUILD_TYPE=Release \
           -DCMAKE_VS_GLOBALS="CLToolExe=cl.exe;CLToolPath=${CCACHE_DIR};TrackFileAccess=false;UseMultiToolTask=true;DebugInformationFormat=OldStyle"
    - name: Build
      shell: bash
      run: |
        VERBOSE=1 cmake --build _build --config Release
